---
- name: install nut server
  package: >
    name={{nut_server_package}}
    state=latest

- name: Install dependencies
  apt:
    name:
      - mosquitto-clients
    state: present
  become: true

- name: Ensure paths exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0700
    owner: "root"
    group: "{{ nut_user }}"
  with_items:
    - {path: "{{ nut_config_path }}/mqttnotify", when: true}

- name: configure ups.conf
  template: >
    src=ups.conf.j2
    dest={{nut_config_path}}/ups.conf
    owner=root
    group={{nut_user}}
    mode=0644
  notify:
    - restart nut-server
    - restart nut-driver

- name: configure upsd.conf
  template: >
    src=upsd.conf.j2
    dest={{nut_config_path}}/upsd.conf
    owner=root
    group={{nut_user}}
    mode=0644
  notify:
    - restart nut-server

- name: configure upsd.users
  template: >
    src=upsd.users.j2
    dest={{nut_config_path}}/upsd.users
    owner=root
    group={{nut_user}}
    mode=0640
  notify:
    - restart nut-server

- name: install udev rules
  copy: >
    src=files/52-nut-usbups.rules
    dest=/etc/udev/rules.d/52-nut-usbups.rules
    mode=0644
    group=root
    owner=root
  notify:
    - restart nut-driver

- name: Copy nutnotifymqtt.sh file
  template:
    src: "nutnotifymqtt.sh.j2"
    dest: "{{ nut_config_path }}/mqttnotify/nutnotifymqtt.sh"
    mode: '0770'
    owner: "{{nut_user}}"
    group: "{{nut_user}}"
